version: 0.2

phases:
  install:
    commands:
    - echo "Installing dependencies..."
    - cd api/get-top-five-metrics
    - pip install -r requirements.txt -t .

  build:
    commands:
    - echo "Build phase completed"

  post_build:
    commands:
    - echo "Creating Lambda deployment package..."
    - zip -r GetTopFiveMetrics.zip . -x "*.git*" -x "*__pycache__*" -x "buildspec.yaml" -x "deployspec.yaml"

artifacts:
  files:
    - api/get-top-five-metrics/GetTopFiveMetrics.zip
  name: BuildOutput
