version: 0.2

env:
  variables:
    VITE_TMDB_API_KEY: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJkY2VkNzUxMWU2MmUwMzUwZDgxNmEyNzA2OGRhOWZiOCIsIm5iZiI6MTc2MjI2OTQ0Mi4wNTQwMDAxLCJzdWIiOiI2OTBhMTkwMjU4ZDQyMTcxN2E0MTM5MzkiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.qQkTLZD12a0juvf0VlXl4WkKsFiLuSighJy0m41frNs"

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
    - echo "Installing dependencies..."
    - ls -ltr
    - cd react-web
    - npm install

  pre_build:
    commands:
    - echo "Preparing build environment..."
    - echo "VITE_TMDB_API_KEY=${VITE_TMDB_API_KEY}" > .env.production
    - echo "VITE_AWS_API_BASE_URL=${VITE_AWS_API_BASE_URL}" >> .env.production
    - echo "Created .env.production:"
    - cat .env.production

  build:
    commands:
    - echo "Building the React project..."
    - cd react-web
    - npm run build
    - echo "Build completed successfully"

artifacts:
  files:
  - '**/*'
  base-directory: react-web/dist
  name: BuildOutput