version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # or whatever version you need
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the project..."
      - npm run build

post_build:
  commands:
    - echo "Deploying build output to S3..."
    # Replace with your actual bucket name
    - aws s3 sync dist s3://msr-staticwebsite-react-movieflix-20251106181800/ --delete
    - echo "Deployment to S3 completed."
