version: 0.2

phases:
  install:
    commands:
    - echo "Installing dependencies..."
    - cd api/create-metrics
    - pip install -r requirements.txt -t .

  build:
    commands:
    - echo "Build phase started"
    - zip -r CreateMovieMetrics.zip . -x "*.git*" -x "*__pycache__*" -x "buildspec.yaml" -x "deployspec.yaml"
    - echo "Build phase completed"

artifacts:
  files:
    - api/create-metrics/CreateMovieMetrics.zip
  name: BuildOutput
